/**
 * Complete list of supported regions from TMDB API
 */
export interface RegionData {
  code: string;
  name: string;
  nativeName: string;
}

export const REGIONS_DATA: RegionData[] = [
  { code: "AD", name: "Andorra", nativeName: "Andorra" },
  {
    code: "AE",
    name: "United Arab Emirates",
    nativeName: "United Arab Emirates",
  },
  { code: "AF", name: "Afghanistan", nativeName: "Afghanistan" },
  { code: "AG", name: "Antigua and Barbuda", nativeName: "Antigua & Barbuda" },
  { code: "AI", name: "Anguilla", nativeName: "Anguilla" },
  { code: "AL", name: "Albania", nativeName: "Albania" },
  { code: "AM", name: "Armenia", nativeName: "Armenia" },
  { code: "AO", name: "Angola", nativeName: "Angola" },
  { code: "AR", name: "Argentina", nativeName: "Argentina" },
  { code: "AS", name: "American Samoa", nativeName: "American Samoa" },
  { code: "AT", name: "Austria", nativeName: "Austria" },
  { code: "AU", name: "Australia", nativeName: "Australia" },
  { code: "AW", name: "Aruba", nativeName: "Aruba" },
  { code: "AZ", name: "Azerbaijan", nativeName: "Azerbaijan" },
  {
    code: "BA",
    name: "Bosnia and Herzegovina",
    nativeName: "Bosnia & Herzegovina",
  },
  { code: "BB", name: "Barbados", nativeName: "Barbados" },
  { code: "BD", name: "Bangladesh", nativeName: "Bangladesh" },
  { code: "BE", name: "Belgium", nativeName: "Belgium" },
  { code: "BF", name: "Burkina Faso", nativeName: "Burkina Faso" },
  { code: "BG", name: "Bulgaria", nativeName: "Bulgaria" },
  { code: "BH", name: "Bahrain", nativeName: "Bahrain" },
  { code: "BI", name: "Burundi", nativeName: "Burundi" },
  { code: "BJ", name: "Benin", nativeName: "Benin" },
  { code: "BM", name: "Bermuda", nativeName: "Bermuda" },
  { code: "BN", name: "Brunei Darussalam", nativeName: "Brunei" },
  { code: "BO", name: "Bolivia", nativeName: "Bolivia" },
  { code: "BR", name: "Brazil", nativeName: "Brazil" },
  { code: "BS", name: "Bahamas", nativeName: "Bahamas" },
  { code: "BT", name: "Bhutan", nativeName: "Bhutan" },
  { code: "BW", name: "Botswana", nativeName: "Botswana" },
  { code: "BY", name: "Belarus", nativeName: "Belarus" },
  { code: "BZ", name: "Belize", nativeName: "Belize" },
  { code: "CA", name: "Canada", nativeName: "Canada" },
  {
    code: "CD",
    name: "Congo",
    nativeName: "Democratic Republic of the Congo (Kinshasa)",
  },
  {
    code: "CF",
    name: "Central African Republic",
    nativeName: "Central African Republic",
  },
  {
    code: "CG",
    name: "Congo",
    nativeName: "Republic of the Congo (Brazzaville)",
  },
  { code: "CH", name: "Switzerland", nativeName: "Switzerland" },
  { code: "CI", name: "Cote D'Ivoire", nativeName: "Côte d'Ivoire" },
  { code: "CK", name: "Cook Islands", nativeName: "Cook Islands" },
  { code: "CL", name: "Chile", nativeName: "Chile" },
  { code: "CM", name: "Cameroon", nativeName: "Cameroon" },
  { code: "CN", name: "China", nativeName: "China" },
  { code: "CO", name: "Colombia", nativeName: "Colombia" },
  { code: "CR", name: "Costa Rica", nativeName: "Costa Rica" },
  { code: "CU", name: "Cuba", nativeName: "Cuba" },
  { code: "CV", name: "Cape Verde", nativeName: "Cape Verde" },
  { code: "CY", name: "Cyprus", nativeName: "Cyprus" },
  { code: "CZ", name: "Czech Republic", nativeName: "Czech Republic" },
  { code: "DE", name: "Germany", nativeName: "Germany" },
  { code: "DJ", name: "Djibouti", nativeName: "Djibouti" },
  { code: "DK", name: "Denmark", nativeName: "Denmark" },
  { code: "DM", name: "Dominica", nativeName: "Dominica" },
  { code: "DO", name: "Dominican Republic", nativeName: "Dominican Republic" },
  { code: "DZ", name: "Algeria", nativeName: "Algeria" },
  { code: "EC", name: "Ecuador", nativeName: "Ecuador" },
  { code: "EE", name: "Estonia", nativeName: "Estonia" },
  { code: "EG", name: "Egypt", nativeName: "Egypt" },
  { code: "EH", name: "Western Sahara", nativeName: "Western Sahara" },
  { code: "ER", name: "Eritrea", nativeName: "Eritrea" },
  { code: "ES", name: "Spain", nativeName: "Spain" },
  { code: "ET", name: "Ethiopia", nativeName: "Ethiopia" },
  { code: "FI", name: "Finland", nativeName: "Finland" },
  { code: "FJ", name: "Fiji", nativeName: "Fiji" },
  { code: "FK", name: "Falkland Islands", nativeName: "Falkland Islands" },
  { code: "FM", name: "Micronesia", nativeName: "Micronesia" },
  { code: "FO", name: "Faeroe Islands", nativeName: "Faroe Islands" },
  { code: "FR", name: "France", nativeName: "France" },
  { code: "GA", name: "Gabon", nativeName: "Gabon" },
  { code: "GB", name: "United Kingdom", nativeName: "United Kingdom" },
  { code: "GD", name: "Grenada", nativeName: "Grenada" },
  { code: "GE", name: "Georgia", nativeName: "Georgia" },
  { code: "GF", name: "French Guiana", nativeName: "French Guiana" },
  { code: "GH", name: "Ghana", nativeName: "Ghana" },
  { code: "GI", name: "Gibraltar", nativeName: "Gibraltar" },
  { code: "GL", name: "Greenland", nativeName: "Greenland" },
  { code: "GM", name: "Gambia", nativeName: "Gambia" },
  { code: "GN", name: "Guinea", nativeName: "Guinea" },
  { code: "GP", name: "Guadaloupe", nativeName: "Guadeloupe" },
  { code: "GQ", name: "Equatorial Guinea", nativeName: "Equatorial Guinea" },
  { code: "GR", name: "Greece", nativeName: "Greece" },
  { code: "GT", name: "Guatemala", nativeName: "Guatemala" },
  { code: "GU", name: "Guam", nativeName: "Guam" },
  { code: "GW", name: "Guinea-Bissau", nativeName: "Guinea-Bissau" },
  { code: "GY", name: "Guyana", nativeName: "Guyana" },
  { code: "HK", name: "Hong Kong", nativeName: "Hong Kong SAR China" },
  { code: "HN", name: "Honduras", nativeName: "Honduras" },
  { code: "HR", name: "Croatia", nativeName: "Croatia" },
  { code: "HT", name: "Haiti", nativeName: "Haiti" },
  { code: "HU", name: "Hungary", nativeName: "Hungary" },
  { code: "ID", name: "Indonesia", nativeName: "Indonesia" },
  { code: "IE", name: "Ireland", nativeName: "Ireland" },
  { code: "IL", name: "Israel", nativeName: "Israel" },
  { code: "IN", name: "India", nativeName: "India" },
  { code: "IQ", name: "Iraq", nativeName: "Iraq" },
  { code: "IR", name: "Iran", nativeName: "Iran" },
  { code: "IS", name: "Iceland", nativeName: "Iceland" },
  { code: "IT", name: "Italy", nativeName: "Italy" },
  { code: "JM", name: "Jamaica", nativeName: "Jamaica" },
  { code: "JO", name: "Jordan", nativeName: "Jordan" },
  { code: "JP", name: "Japan", nativeName: "Japan" },
  { code: "KE", name: "Kenya", nativeName: "Kenya" },
  { code: "KG", name: "Kyrgyz Republic", nativeName: "Kyrgyzstan" },
  { code: "KH", name: "Cambodia", nativeName: "Cambodia" },
  { code: "KI", name: "Kiribati", nativeName: "Kiribati" },
  { code: "KM", name: "Comoros", nativeName: "Comoros" },
  { code: "KN", name: "St. Kitts and Nevis", nativeName: "St. Kitts & Nevis" },
  { code: "KP", name: "North Korea", nativeName: "North Korea" },
  { code: "KR", name: "South Korea", nativeName: "South Korea" },
  { code: "KW", name: "Kuwait", nativeName: "Kuwait" },
  { code: "KY", name: "Cayman Islands", nativeName: "Cayman Islands" },
  { code: "KZ", name: "Kazakhstan", nativeName: "Kazakhstan" },
  { code: "LA", name: "Lao People's Democratic Republic", nativeName: "Laos" },
  { code: "LB", name: "Lebanon", nativeName: "Lebanon" },
  { code: "LC", name: "St. Lucia", nativeName: "St. Lucia" },
  { code: "LI", name: "Liechtenstein", nativeName: "Liechtenstein" },
  { code: "LK", name: "Sri Lanka", nativeName: "Sri Lanka" },
  { code: "LR", name: "Liberia", nativeName: "Liberia" },
  { code: "LS", name: "Lesotho", nativeName: "Lesotho" },
  { code: "LT", name: "Lithuania", nativeName: "Lithuania" },
  { code: "LU", name: "Luxembourg", nativeName: "Luxembourg" },
  { code: "LV", name: "Latvia", nativeName: "Latvia" },
  { code: "LY", name: "Libyan Arab Jamahiriya", nativeName: "Libya" },
  { code: "MA", name: "Morocco", nativeName: "Morocco" },
  { code: "MC", name: "Monaco", nativeName: "Monaco" },
  { code: "MD", name: "Moldova", nativeName: "Moldova" },
  { code: "ME", name: "Montenegro", nativeName: "Montenegro" },
  { code: "MG", name: "Madagascar", nativeName: "Madagascar" },
  { code: "MH", name: "Marshall Islands", nativeName: "Marshall Islands" },
  { code: "MK", name: "Macedonia", nativeName: "Macedonia" },
  { code: "ML", name: "Mali", nativeName: "Mali" },
  { code: "MM", name: "Myanmar", nativeName: "Myanmar (Burma)" },
  { code: "MN", name: "Mongolia", nativeName: "Mongolia" },
  { code: "MO", name: "Macao", nativeName: "Macau SAR China" },
  {
    code: "MP",
    name: "Northern Mariana Islands",
    nativeName: "Northern Mariana Islands",
  },
  { code: "MQ", name: "Martinique", nativeName: "Martinique" },
  { code: "MR", name: "Mauritania", nativeName: "Mauritania" },
  { code: "MS", name: "Montserrat", nativeName: "Montserrat" },
  { code: "MT", name: "Malta", nativeName: "Malta" },
  { code: "MU", name: "Mauritius", nativeName: "Mauritius" },
  { code: "MV", name: "Maldives", nativeName: "Maldives" },
  { code: "MW", name: "Malawi", nativeName: "Malawi" },
  { code: "MX", name: "Mexico", nativeName: "Mexico" },
  { code: "MY", name: "Malaysia", nativeName: "Malaysia" },
  { code: "MZ", name: "Mozambique", nativeName: "Mozambique" },
  { code: "NA", name: "Namibia", nativeName: "Namibia" },
  { code: "NC", name: "New Caledonia", nativeName: "New Caledonia" },
  { code: "NE", name: "Niger", nativeName: "Niger" },
  { code: "NF", name: "Norfolk Island", nativeName: "Norfolk Island" },
  { code: "NG", name: "Nigeria", nativeName: "Nigeria" },
  { code: "NI", name: "Nicaragua", nativeName: "Nicaragua" },
  { code: "NL", name: "Netherlands", nativeName: "Netherlands" },
  { code: "NO", name: "Norway", nativeName: "Norway" },
  { code: "NP", name: "Nepal", nativeName: "Nepal" },
  { code: "NR", name: "Nauru", nativeName: "Nauru" },
  { code: "NU", name: "Niue", nativeName: "Niue" },
  { code: "NZ", name: "New Zealand", nativeName: "New Zealand" },
  { code: "OM", name: "Oman", nativeName: "Oman" },
  { code: "PA", name: "Panama", nativeName: "Panama" },
  { code: "PE", name: "Peru", nativeName: "Peru" },
  { code: "PF", name: "French Polynesia", nativeName: "French Polynesia" },
  { code: "PG", name: "Papua New Guinea", nativeName: "Papua New Guinea" },
  { code: "PH", name: "Philippines", nativeName: "Philippines" },
  { code: "PK", name: "Pakistan", nativeName: "Pakistan" },
  { code: "PL", name: "Poland", nativeName: "Poland" },
  {
    code: "PM",
    name: "St. Pierre and Miquelon",
    nativeName: "St. Pierre & Miquelon",
  },
  { code: "PN", name: "Pitcairn Island", nativeName: "Pitcairn Islands" },
  { code: "PR", name: "Puerto Rico", nativeName: "Puerto Rico" },
  {
    code: "PS",
    name: "Palestinian Territory",
    nativeName: "Palestinian Territories",
  },
  { code: "PT", name: "Portugal", nativeName: "Portugal" },
  { code: "PW", name: "Palau", nativeName: "Palau" },
  { code: "PY", name: "Paraguay", nativeName: "Paraguay" },
  { code: "QA", name: "Qatar", nativeName: "Qatar" },
  { code: "RE", name: "Reunion", nativeName: "Réunion" },
  { code: "RO", name: "Romania", nativeName: "Romania" },
  { code: "RS", name: "Serbia", nativeName: "Serbia" },
  { code: "RU", name: "Russia", nativeName: "Russia" },
  { code: "RW", name: "Rwanda", nativeName: "Rwanda" },
  { code: "SA", name: "Saudi Arabia", nativeName: "Saudi Arabia" },
  { code: "SB", name: "Solomon Islands", nativeName: "Solomon Islands" },
  { code: "SC", name: "Seychelles", nativeName: "Seychelles" },
  { code: "SD", name: "Sudan", nativeName: "Sudan" },
  { code: "SE", name: "Sweden", nativeName: "Sweden" },
  { code: "SG", name: "Singapore", nativeName: "Singapore" },
  { code: "SH", name: "St. Helena", nativeName: "St. Helena" },
  { code: "SI", name: "Slovenia", nativeName: "Slovenia" },
  { code: "SK", name: "Slovakia", nativeName: "Slovakia" },
  { code: "SL", name: "Sierra Leone", nativeName: "Sierra Leone" },
  { code: "SM", name: "San Marino", nativeName: "San Marino" },
  { code: "SN", name: "Senegal", nativeName: "Senegal" },
  { code: "SO", name: "Somalia", nativeName: "Somalia" },
  { code: "SR", name: "Suriname", nativeName: "Suriname" },
  { code: "SS", name: "South Sudan", nativeName: "South Sudan" },
  {
    code: "ST",
    name: "Sao Tome and Principe",
    nativeName: "São Tomé & Príncipe",
  },
  { code: "SV", name: "El Salvador", nativeName: "El Salvador" },
  { code: "SY", name: "Syrian Arab Republic", nativeName: "Syria" },
  { code: "SZ", name: "Swaziland", nativeName: "Eswatini (Swaziland)" },
  {
    code: "TC",
    name: "Turks and Caicos Islands",
    nativeName: "Turks & Caicos Islands",
  },
  { code: "TD", name: "Chad", nativeName: "Chad" },
  {
    code: "TF",
    name: "French Southern Territories",
    nativeName: "French Southern Territories",
  },
  { code: "TG", name: "Togo", nativeName: "Togo" },
  { code: "TH", name: "Thailand", nativeName: "Thailand" },
  { code: "TJ", name: "Tajikistan", nativeName: "Tajikistan" },
  { code: "TK", name: "Tokelau", nativeName: "Tokelau" },
  { code: "TL", name: "Timor-Leste", nativeName: "Timor-Leste" },
  { code: "TM", name: "Turkmenistan", nativeName: "Turkmenistan" },
  { code: "TN", name: "Tunisia", nativeName: "Tunisia" },
  { code: "TO", name: "Tonga", nativeName: "Tonga" },
  { code: "TR", name: "Turkey", nativeName: "Turkey" },
  { code: "TT", name: "Trinidad and Tobago", nativeName: "Trinidad & Tobago" },
  { code: "TV", name: "Tuvalu", nativeName: "Tuvalu" },
  { code: "TW", name: "Taiwan", nativeName: "Taiwan" },
  { code: "TZ", name: "Tanzania", nativeName: "Tanzania" },
  { code: "UA", name: "Ukraine", nativeName: "Ukraine" },
  { code: "UG", name: "Uganda", nativeName: "Uganda" },
  { code: "US", name: "United States of America", nativeName: "United States" },
  { code: "UY", name: "Uruguay", nativeName: "Uruguay" },
  { code: "UZ", name: "Uzbekistan", nativeName: "Uzbekistan" },
  { code: "VA", name: "Holy See", nativeName: "Vatican City" },
  {
    code: "VC",
    name: "St. Vincent and the Grenadines",
    nativeName: "St. Vincent & Grenadines",
  },
  { code: "VE", name: "Venezuela", nativeName: "Venezuela" },
  {
    code: "VG",
    name: "British Virgin Islands",
    nativeName: "British Virgin Islands",
  },
  { code: "VI", name: "US Virgin Islands", nativeName: "U.S. Virgin Islands" },
  { code: "VN", name: "Vietnam", nativeName: "Vietnam" },
  { code: "VU", name: "Vanuatu", nativeName: "Vanuatu" },
  {
    code: "WF",
    name: "Wallis and Futuna Islands",
    nativeName: "Wallis & Futuna",
  },
  { code: "WS", name: "Samoa", nativeName: "Samoa" },
  { code: "XK", name: "Kosovo", nativeName: "Kosovo" },
  { code: "YE", name: "Yemen", nativeName: "Yemen" },
  { code: "YT", name: "Mayotte", nativeName: "Mayotte" },
  { code: "ZA", name: "South Africa", nativeName: "South Africa" },
  { code: "ZM", name: "Zambia", nativeName: "Zambia" },
  { code: "ZW", name: "Zimbabwe", nativeName: "Zimbabwe" },
];

/**
 * Get all valid region codes
 */
export function getAllRegionCodes(): string[] {
  return REGIONS_DATA.map((region) => region.code);
}

/**
 * Check if a region code is valid
 */
export function isValidRegionCode(code: string): boolean {
  return REGIONS_DATA.some((region) => region.code === code);
}

/**
 * Get region data by code
 */
export function getRegionDataByCode(code: string): RegionData | undefined {
  return REGIONS_DATA.find((region) => region.code === code);
}

/**
 * Sort regions by name for display purposes
 */
export function getSortedRegions(): RegionData[] {
  return [...REGIONS_DATA].sort((a, b) =>
    (a.name || "").localeCompare(b.name || "")
  );
}

/**
 * Get popular/common regions to show at the top
 */
export function getPopularRegions(): RegionData[] {
  const popularCodes = [
    "US",
    "GB",
    "DE",
    "FR",
    "ES",
    "IT",
    "CA",
    "AU",
    "JP",
    "KR",
    "BR",
    "MX",
    "IN",
    "CZ",
  ];
  return popularCodes
    .map((code) => getRegionDataByCode(code))
    .filter((region): region is RegionData => region !== undefined);
}
